In [2]:
import imdb

In [3]:
import numpy as np

In [5]:
%time train = imdb.IMDBdata("aclImdb_small/train")

CPU times: user 20.9 s, sys: 1.61 s, total: 22.5 s
Wall time: 26 s


In [31]:
print(len(train.vocab.GetWords()))

58162


In [32]:
w = np.random.random(train.X.shape[1])
print(w)

[ 0.74795864  0.3652866   0.93259164 ...,  0.19210757  0.35961315
  0.78308187]


In [33]:
train.X.shape

(7222, 58162)

In [38]:
print(train.X[0,:])

  (0, 40868)	1
  (0, 40867)	1
  (0, 40866)	1
  (0, 40865)	1
  (0, 40864)	1
  (0, 40863)	1
  (0, 40862)	1
  (0, 40861)	1
  (0, 40860)	1
  (0, 40859)	1
  (0, 40858)	1
  (0, 40857)	1
  (0, 40856)	1
  (0, 40855)	2
  (0, 40854)	1
  (0, 40853)	1
  (0, 40852)	1
  (0, 40851)	1
  (0, 40850)	1
  (0, 40849)	2
  (0, 40848)	1
  (0, 40847)	1
  (0, 40846)	1
  (0, 40845)	1
  (0, 40844)	1
  :	:
  (0, 82)	7
  (0, 75)	18
  (0, 72)	1
  (0, 68)	4
  (0, 60)	1
  (0, 50)	14
  (0, 48)	1
  (0, 46)	4
  (0, 43)	1
  (0, 40)	32
  (0, 36)	7
  (0, 35)	3
  (0, 33)	15
  (0, 31)	12
  (0, 30)	5
  (0, 23)	15
  (0, 22)	2
  (0, 21)	8
  (0, 20)	3
  (0, 17)	1
  (0, 16)	12
  (0, 14)	16
  (0, 12)	8
  (0, 9)	2
  (0, 4)	5


In [39]:
print(train.vocab.GetWord(75))

.


In [40]:
%%time
train.X[0,:].dot(w)

CPU times: user 433 µs, sys: 97 µs, total: 530 µs
Wall time: 457 µs


array([ 299.08906488])

In [41]:
%%time
sum = 0
for i in range(train.X.shape[1]):
    sum += train.X[0,i] * w[i]
print(sum)

299.089064884
CPU times: user 1.99 s, sys: 18.3 ms, total: 2.01 s
Wall time: 2.05 s


In [42]:
train.Y

array([-1., -1., -1., ..., -1.,  1., -1.])

In [58]:
print(train.X[train.Y == -1,:])

  (0, 4)	5
  (0, 9)	2
  (0, 12)	8
  (0, 14)	16
  (0, 16)	12
  (0, 17)	1
  (0, 20)	3
  (0, 21)	8
  (0, 22)	2
  (0, 23)	15
  (0, 30)	5
  (0, 31)	12
  (0, 33)	15
  (0, 35)	3
  (0, 36)	7
  (0, 40)	32
  (0, 43)	1
  (0, 46)	4
  (0, 48)	1
  (0, 50)	14
  (0, 60)	1
  (0, 68)	4
  (0, 72)	1
  (0, 75)	18
  (0, 82)	7
  :	:
  (3610, 1671)	1
  (3610, 1950)	1
  (3610, 2222)	1
  (3610, 2255)	1
  (3610, 2298)	2
  (3610, 2517)	3
  (3610, 2610)	1
  (3610, 2661)	1
  (3610, 2988)	1
  (3610, 4374)	1
  (3610, 4458)	1
  (3610, 5758)	1
  (3610, 6782)	1
  (3610, 7162)	2
  (3610, 7480)	1
  (3610, 8454)	2
  (3610, 8563)	1
  (3610, 8606)	2
  (3610, 10717)	1
  (3610, 13950)	1
  (3610, 15308)	1
  (3610, 21104)	1
  (3610, 30866)	1
  (3610, 40271)	1
  (3610, 48694)	1


In [61]:
word_counts = np.array(train.X[train.Y == -1,:].sum(axis=0)).flatten()
word_counts

array([  83,  493, 6948, ...,    1,    1,    1], dtype=int64)

In [62]:
sorted_words = list(reversed(np.argsort(word_counts)))
sorted_words[0:10]

[40, 50, 75, 23, 82, 33, 14, 234, 231, 233]

In [45]:
sorted_words[0]

40

In [64]:
train.vocab.GetWord(sorted_words[1])

'.'

In [14]:
[train.vocab.GetWord(sorted_words[x]) for x in range(10)]

['the', ',', '.', 'a', 'and', 'to', 'of', '>', '<', '/']

In [15]:
x = range(10)

In [16]:
list(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
[a + 1 for a in x]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]